export CROSS_TARGET=arm64-unknown-linux-musl

ARCH = aarch64

CC := xcross cc -static
OBJDUMP := xcross objdump

# 用自己安装的工具链
# CC := aarch64-linux-gnu-gcc
# OBJDUMP := aarch64-linux-gnu-objdump

include ../common/basic.mk