export CROSS_TARGET=mips64el-unknown-linux-muslsf
# mips-unknown-linux-musl
# mipsel-unknown-linux-muslsf
# https://hub.docker.com/r/ahuszagh/cross/tags?page=4&page_size=&name=mips&ordering=

ARCH = mips64el
CC = xcross cc -static
OBJDUMP = xcross objdump

include ../common/basic.mk