

all:
	make -C src/x86_64
	make -C src/aarch64
	make -C src/arm
	make -C src/mips
	make -C src/mipsel
	make -C src/mips64
	make -C src/mips64el
	make -C src/ppc64
	make -C src/ppc64le
	make -C src/riscv32
	make -C src/riscv64